name: Update Exchange Rates

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install dependencies
        run: npm install
      
      - name: Fetch and update rates
        run: node scripts/update-rates.js
      
      - name: Commit and push changes
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "Exchange Rate Bot"
          git add latest.json
          git diff --staged --quiet || git commit -m "Update rates - $(date -u +'%Y-%m-%d %H:%M UTC')"
          git push
      
      - name: Purge JSDelivr CDN cache
        run: |
          sleep 10
          curl https://purge.jsdelivr.net/gh/anvme/currency@main/latest.json
          echo "✓ CDN cache purged"
